### ISSUE TITLE
open-gds - gds.debug.arrow not found

### ISSUE THREAD

**Issue by aph5nt** [DozerDB/dozerdb-plugin#38]
when I try to do

```python
 graph_database_science = GraphDataScience(graph_db_url, auth=(graph_db_user, graph_db_password), database=args.network)
```

I get the following exception

```python
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureNotFound} {message: There is no procedure with the name `gds.debug.arrow` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.}
```

My dozer is running in docker-compose

```yaml
services:
  dozer-instance:
    container_name:   dozer-instance
    image: graphstack/dozerdb:5.25.1
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
      - "7473:7473"  # HTTPS
    environment:
      - NEO4J_AUTH=neo4j/secret!
      - NEO4J_server_memory_pagecache_size=8G
      - NEO4J_server_memory_heap_initial__size=8G
      - NEO4J_server_memory_heap_max__size=16G
      - NEO4J_server_directories_plugins=/var/lib/neo4j/labs

      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,dbms.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*,dbms.*
    volumes:
      -  dozer-instance-data:/data
      -  dozer-instance-logs:/logs
      -  dozer-instance-import:/var/lib/neo4j/import
      - "./open-gds-2.12.0.jar:/plugins/open-gds-2.12.0.jar"
      - "./open-gds-2.12.0.jar:/var/lib/neo4j/labs/open-gds-2.12.0.jar"
    restart: unless-stopped
```
