### ISSUE TITLE
Installing with Docker-Compose?

### ISSUE THREAD

**Issue by kaumudpa** [DozerDB/dozerdb-plugin#5]
How do we get this working with a custom Docker Compose instance of neo4j - i.e. DozerDB as a plugin.

My Docker Compose files looks like -

```
version: "3.3"
services:
  neo4j:
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    volumes:
      - /DATA/AppData/neo4j/data:/data
      - /DATA/AppData/neo4j/logs:/logs
      - /DATA/AppData/neo4j/import:/var/lib/neo4j/import
      - /DATA/AppData/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
    image: neo4j:latest
    restart: always
    logging:
      #      driver: none
      options:
        max-size: 10m
        max-file: "3"
networks: {}
```

**Comment by jmsuhy** [comment]
Try this:
version: '3.3'
services:
    gdb:
        image: 'graphstack/dozerdb:5.15.0.0-alpha.1'
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687
        volumes:
            - ./gdb/data:/data
            - ./gdb/plugins:/plugins
            - ./gdb/conf:/conf
            - ./gdb/import:/import
            - ./gdb/logs:/logs
            - ./gdb/metrics:/metrics
        environment:
        # For other environment options see: https://neo4j.com/docs/operations-manual/current/docker/ref-settings/
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true 
            #- NEO4J_server_memory_heap_initial__size=4g
            #- NEO4J_server_memory_heap_max__size=4g
            #- NEO4J_server_memory_pagecache_size=8g

**Comment by jmsuhy** [comment]
Closing this ticket, if it was not resolved for you, then we can re-open it.

**Comment by captainst** [comment]
@jmsuhy Hi John, I am also using neo4j docker container. As I can't mount **lib** directory, I tried the **plugins** directory.

I used the following docker-compose:
```

version: '3'
services:
  neo4j-dozerDB:
    image: neo4j:5.26.3-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/123456
      CLASSPATH_PREFIX: /var/lib/neo4j/plugins/dozerdb-plugin-5.26.3.0.jar
    volumes:
      - ./data:/data
      - ./plugins:/var/lib/neo4j/plugins
```
It seems to work. But on the web-page it is written: Download the plugin to your $NEO4J_HOME/lib folder , not the $NEO4J_HOME/plugins folder. I am wondering whether putting the **dozerdb-plugin** inside the plugins folder would have any impact ?

Many thanks!
